PROCESS BEFORE OUTPUT.
 MODULE STATUS_0110.

  CALL SUBSCREEN aktivite INCLUDING sy-cprog '0111'.
  CALL SUBSCREEN onay     INCLUDING sy-cprog '0112'.
*

PROCESS AFTER INPUT.
 MODULE USER_COMMAND_0110.

  CALL SUBSCREEN aktivite.
  CALL SUBSCREEN onay    .
