PROCESS BEFORE OUTPUT.
 MODULE STATUS_0100.
  CALL SUBSCREEN table       INCLUDING sy-cprog '0110'.
  CALL SUBSCREEN main_screen INCLUDING sy-cprog '0101'.
*
PROCESS AFTER INPUT.
 MODULE USER_COMMAND_0100.


  CALL SUBSCREEN table      .
  CALL SUBSCREEN main_screen.
